export const analytics = {
  label: 'Analytics',
  list: [
    'Excel',
    'Keynote, SQL',
    'Python',
    'Pandas',
    'Power BI',
    'Tableau',
    'QlikView',
    'Miro',
    'Visio',
    'UML',
    'BPMN',
    'Confluence',
    'Google Analytics',
    'Heatmap',
    'Looker',
    'Pendo',
    'Mixpanel',
    'HockeyStack',
    'Mode',
    'Affise',
  ],
};
