export const devOps = {
  label: 'DevOps',
  list: [
    'Jenkins',
    'TeamCity',
    'GitLab',
    'Bamboo',
    'Github Actions',
    'AWS CodePipeline',
    'Terraform',
    'Puppet',
    'Ansible',
    'AWS',
    'Google Cloud Platform',
    'Microsoft Azure',
    'Huawei Cloud',
    'Яндекс Облако',
    'Mail.ru Cloud Solutions',
    'Prometheus',
    'Grafana',
    'ELK Stack',
    'Graylog',
    'Grafana',
    'Jaeger',
    'Docker',
    'Podman',
    'Kubernetes',
    'Rancher',
    'Serverless',
  ],
};
