export const frontend = {
  label: 'Frontend',
  list: [
    'JavaScript',
    'Typescript',
    'HTML5',
    'CSS3',
    'SASS',
    'Less',
    'React',
    'Vue.js',
    'Angular 6+',
    'Redux',
    'redux-saga',
    'redux-toolkit',
    'vuex',
    'Rest',
    'WebSockets',
    'css modules',
    'css-in-js',
    'docker',
    'postman',
    'jest',
    'SSR',
    'styled-component',
    'Flux',
    'Mobx',
    'Redux Thunk',
    'next js / nuxt js',
    'Axios',
    'Formik',
    'Redux Form',
    'Yep',
    'Husky',
    'ESlint',
    'Prettier',
    'Commitlint',
    'JSLint',
    'Ant Design',
    'Material UI',
    'webpack',
    'gulp.js',
    'Babel',
    'ES6',
    'Stylus',
    'CoffeeScript',
    'Rollup',
    'Lerna',
    'Storybook',
    'react-query',
    'Apollo Client',
  ],
};
