export const pm = {
  label: 'Product management / Project management',
  list: [
    'Pendo',
    'Amplitude',
    'ProductPlan',
    'SurveyMonkey',
    'Typeform',
    'Zoom',
    'Gartner',
    'Sirius Decisions',
    'Slack',
    'Confluence',
    'PowerPoint',
    'Keynote',
    'Jira',
    'Pivotal Tracker',
    'Trello',
    'Split.io',
    'LaunchDarkly',
    'FullStory',
    'Hotjar',
    'Evernote',
    'Google Drive',
  ],
};
